version: '3'
services:
  apple_watch:
    image: watch_monitor
    container_name: apple_watch
    build: .
    ports:
      - "127.0.0.1:600:600"
    depends_on: # other containers it needs in order to run
      - databaseapple
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=databaseapple
    volumes:
      - ./import:/app/import
    restart: always

  databaseapple:
    image: postgres
    container_name: database_apple
    ports:
      - "5424:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always